### ISSUE TITLE
FeatureIndexManager FeatureIndexType.RTREE index error

### ISSUE THREAD

**Issue by enisozgur** [ngageoint/geopackage-android#62]
Hi
trying to create a table.
I want to use rtree. I get an error in ST_Min function

My Code Is;

FeatureIndexManager indexer = new FeatureIndexManager(_context, _geoPackage, name);
indexer.setIndexLocation(FeatureIndexType.RTREE);
indexer.index();

java.lang.UnsupportedOperationException: User defined SQL functions are not supported. name: ST_MinX
mil.nga.geopackage.extension.RTreeIndexExtension.createFunction(RTreeIndexExtension.java:120)

thanks

**Comment by bosborn** [comment]
RTree is currently supported as read only in Android due to the SQLite Android Bindings lack of User defined function support.  See also #60 and #49.

An RTree created by [Java](https://github.com/ngageoint/geopackage-java), [JS](https://github.com/ngageoint/geopackage-js), [iOS](https://github.com/ngageoint/geopackage-ios), GDAL, QGIS, etc is supported in the Android library as read only.  For an index created/used within the Android library & stored in the GeoPackage, try [FeatureIndexType.GEOPACKAGE](https://github.com/ngageoint/geopackage-android/blob/36b7e6d309bc0a63424af0b80de974ed2ebacd4f/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexType.java#L19).

**Comment by enisozgur** [comment]
Thanks Bosborn...
